apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-flask
spec:
  selector:
    matchLabels:
      app: simple-flask
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: simple-flask
    spec:
      containers:
      - name: simple-flask
        image: registry.hub.docker.com/ehan1990/simple-flask:1.1.0-dev.2
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: lb
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8080
  selector:
    app: simple-flask
